name: Continual on PR
on: pull_request
env:
  CONTINUAL_API_KEY: ${{ secrets.CONTINUAL_API_KEY }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
  pull-requests: write
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Set unique run ID
        run: |
          CONTINUAL_RUN_ID=$GITHUB_RUN_ID-$GITHUB_RUN_ATTEMPT
          echo "Using run ID $CONTINUAL_RUN_ID"
          echo "CONTINUAL_RUN_ID=$CONTINUAL_RUN_ID" >> $GITHUB_ENV
      - name: Install
        run: |
          python -m pip install 'continual>=2.0.0a'
      - name: Verify setup
        run: |
          python -c 'import continual; print(continual.Client().version())'
          python -c 'import continual; print(continual.Client().config.show())'
      - name: Create Continual environment
        run: |
          continual_environment_id="pr-$GITHUB_PR_NUMBER"         
          create_result=`python -c "import continual; c = continual.Client(); print(c.projects.get(c.config.project).environments.create(id='$continual_environment_id', replace_if_exists=True).name)"`
          if ! grep -q "^projects/" <<< "$create_result"; then
            exit 1;
          else
            CONTINUAL_ENVIRONMENT=$continual_environment_id
          fi
          echo "Using Continual Environment $CONTINUAL_ENVIRONMENT"
          echo "CONTINUAL_ENVIRONMENT=$CONTINUAL_ENVIRONMENT" >> $GITHUB_ENV
        env:
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
      - name: Run
        run: |
          python run.py
      - name: Get Continual run URL
        run: |
          CONTINUAL_RUN_URL=$(python -c 'import continual; print(continual.Client().runs.get("'$CONTINUAL_RUN_ID'").continual_app_url)')
          echo "$CONTINUAL_RUN_URL"
          echo "CONTINUAL_RUN_URL=$CONTINUAL_RUN_URL" >> $GITHUB_ENV
      - name: Add PR comment
        run: |
          gh pr comment $PR_NUMBER \
            --body "Continual run: [$CONTINUAL_RUN_URL]($CONTINUAL_RUN_URL)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
